export default function TopNav() {
  return (
    <div className="text-foreground">
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
    </div>
  )
}
