export default function TopNav() {
  return (
    <div className="text-foreground pt-10 pb-56">
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p>nav item</p>
      <p> ===== last =====</p>
    </div>
  )
}
